import = ["~/.config/alacritty/themes/tokyo-night.toml"]
[shell]
program = "/bin/zsh"
[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"
[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
