[theme.colors]
# monokai theme
comment = "#797979"
white = "#d6d6d6"
yellow = "#e5b567"
green = "#b4d273"
orange = "#e87d3e"
purple = "#9e86c8"
pink = "#b05279"
blue = "#6c99bb"

alert = "#e5b567 bold"
info = "#e87d3e bold"
info2 = "#e5b567"
link = "#b4d273 underline"
main = "#d6d6d6 bold"
sub = "#d6d6d6"
status = "#b05279 bold"

[formats]
page_links = "[info]{title}[/info]\nOut: {out_links.href}\nIn: {in_links.href}"
[queries]
reduce_test = "list pages {lists.*.text} where any lists.*.text has business"
[macros]
not_done = "tasks --filter 'status = not done'"
latest = "list pages --sort 'modified_at desc'"