[theme.colors]
#monokai theme
# comment = "#797979"
# white = "#d6d6d6"
# yellow = "#e5b567"
# green = "#b4d273"
# orange = "#e87d3e"
# purple = "#9e86c8"
# pink = "#b05279"
# blue = "#6c99bb"

# alert = "#e5b567 bold"
# info = "#e87d3e bold"
# info2 = "#e5b567"
# link = "#b4d273 underline"
# main = "#d6d6d6 bold"
# sub = "#d6d6d6"
# status = "#b05279 bold"

# dracula theme
black = "#282a36"
gray = "#44475a"
white = "#f8f8f2"
slate = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

alert = "#ff5555"
info = "#bd93f9 bold"
info2 = "#bd93f9"
link = "#6272a4 underline"
main = "#50fa7b"
sub = "#f8f8f2"
status = "#8be9fd"

[formats]
page_links = "[info]{title}[/info]\nOut: {out_links.href}\nIn: {in_links.href}"
[queries]
reduce_test = "list pages {lists.*.text} where any lists.*.text has business"
[macros]
zk_todo = "tasks --page 'title = zenkat-todo' --filter 'status = not done'"
latest_5 = "list pages --sort 'modified_at asc' --limit -5"
latest_10 = "list pages --sort 'modified_at asc' --limit -10"
not_done = "tasks --filter 'status = not done'"
latest = "list pages --sort 'modified_at asc'"